CREATE DATABASE IF NOT EXISTS AML_ODS COMMENT '反洗钱ODS层数据库' LOCATION '/user/hive/warehouse/AML_ODS.db';

CREATE EXTERNAL
TABLE IF NOT EXISTS AML_ODS.ODS_AML_ACCOUNT_MASTER (
    ACCOUNT_ID BIGINT COMMENT '账户唯一标识ID',
    ACCT_NO STRING COMMENT '账户号码(业务主键)',
    CUSTOMER_ID BIGINT COMMENT '关联账户ID(外键)',
    ACCT_TYPE STRING COMMENT '账户类型',
    CURRENCY STRING COMMENT '账户币种',
    OPEN_DATE DATE COMMENT '账户开户日期',
    CLOSE_DATE DATE COMMENT '账户销户日期 (NULL表示未销户)',
    STATUS STRING COMMENT '账户状态',
    CURRENT_BALANCE BIGINT COMMENT '当前余额',
    AVG_DAILY_BALANCE BIGINT COMMENT '日均余额 (可定期计算)',
    LAST_TXN_DATE DATE COMMENT '最后交易日期',
    CHANNEL_OPEN STRING COMMENT '开户渠道',
    BRANCH_CODE STRING COMMENT '开户网点代码',
    BRANCH_NAME STRING COMMENT '开户网点名称',
    CREATED_BY STRING COMMENT '创建人',
    CREATED_DATE DATE COMMENT '创建日期',
    UPDATED_BY STRING COMMENT '更新人',
    UPDATED_DATE DATE COMMENT '更新日期'
) COMMENT '账户主表' PARTITIONED BY (ETL_DATE STRING) STORED AS ORC LOCATION '/user/hive/warehouse/AML_ODS.db/ODS_AML_ACCOUNT_MASTER' TBLPROPERTIES ("orc.compress" = "SNAPPY");

CREATE EXTERNAL
TABLE IF NOT EXISTS AML_ODS.ODS_AML_ALERT (
    ALERT_ID BIGINT COMMENT '预警唯一标识ID',
    ALERT_NO STRING COMMENT '预警编号 (业务主键)',
    CUSTOMER_ID BIGINT COMMENT '关联客户ID (外键)',
    ACCOUNT_ID BIGINT COMMENT '关联客户ID (外键)',
    RULE_ID STRING COMMENT '触发规则ID (或模型ID)',
    RULE_NAME STRING COMMENT '触发规则/模型名称',
    ALERT_TYPE STRING COMMENT '预警类型 (RULE:规则, MODEL:模型)',
    ALERT_DATE DATE COMMENT '预警生成日期',
    ALERT_TIME TIMESTAMP COMMENT '预警生成时间戳',
    ALERT_STATUS STRING COMMENT '预警状态 (PENDING:待处理, REVIEWING:审核中, DISMISSED:排除, CONFIRMED:确认)',
    SEVERITY_LEVEL STRING COMMENT '严重等级 (LOW, MEDIUM, HIGH, CRITICAL)',
    SCORE BIGINT COMMENT '模型评分 (若由模型触发)',
    TRIGGER_AMOUNT BIGINT COMMENT '触发交易金额',
    TRIGGER_TXN_COUNT BIGINT COMMENT '触发期间交易笔数',
    DESCRIPTION STRING COMMENT '预警描述 (规则/模型触发原因简述)',
    ASSIGNED_TO STRING COMMENT '分配给 (分析师)',
    ASSIGNED_DATE DATE COMMENT '分配日期',
    REVIEWED_BY STRING COMMENT '审核人',
    REVIEWED_DATE DATE COMMENT '审核日期',
    COMMENTS STRING COMMENT '审核详细意见',
    STR_NO STRING COMMENT '关联的可疑交易报告编号 (确认后生成)',
    CREATED_DATE DATE COMMENT '创建日期',
    UPDATED_DATE DATE COMMENT '更新日期'
) COMMENT '预警表' PARTITIONED BY (ETL_DATE STRING) STORED AS ORC LOCATION '/user/hive/warehouse/AML_ODS.db/ODS_AML_ALERT' TBLPROPERTIES ("orc.compress" = "SNAPPY");

CREATE EXTERNAL
TABLE IF NOT EXISTS AML_ODS.ODS_AML_CUSTOMER_MASTER (
    CUSTOMER_ID BIGINT COMMENT '客户唯一标识ID (主键)',
    CUST_NO STRING COMMENT '客户编号 (业务主键, 唯一)',
    CUST_NAME STRING COMMENT '客户姓名 (个人) / 公司名称 (对公)',
    CUST_TYPE STRING COMMENT '客户类型 (IND:个人, CORP:对公)',
    ID_TYPE STRING COMMENT '证件类型 (ID_CARD:身份证, PASSPORT:护照, BUS_LIC:营业执照等)',
    ID_NO STRING COMMENT '证件号码',
    GENDER STRING COMMENT '性别 (仅个人)',
    BIRTH_DATE DATE COMMENT '出生日期 (仅个人)',
    NATIONALITY STRING COMMENT '国籍',
    RESIDENCE_COUNTRY STRING COMMENT '居住国家',
    RESIDENCE_CITY STRING COMMENT '居住城市',
    ADDRESS STRING COMMENT '详细地址',
    PHONE STRING COMMENT '联系电话',
    EMAIL STRING COMMENT '电子邮箱',
    OCCUPATION STRING COMMENT '职业 (仅个人)',
    INDUSTRY STRING COMMENT '所属行业 (仅对公)',
    ANNUAL_INCOME BIGINT COMMENT '年收入 (估算)',
    SOURCE_OF_FUNDS STRING COMMENT '资金来源 (工资、投资、经营等)',
    PURPOSE_OF_ACCOUNT STRING COMMENT '账户用途 (储蓄、投资、贸易等)',
    RISK_LEVEL STRING COMMENT '当前风险等级 (LOW, MEDIUM, HIGH, VERY_HIGH)',
    RISK_LEVEL_SOURCE STRING COMMENT '风险等级来源 (MANUAL:人工, AUTO:系统自动)',
    RISK_ASSESS_DATE DATE COMMENT '最近一次风险评估日期',
    OPEN_DATE DATE COMMENT '客户开户日期',
    CLOSE_DATE DATE COMMENT '客户销户日期 (NULL表示未销户)',
    STATUS STRING COMMENT '客户状态 (ACTIVE:活跃, INACTIVE:休眠, CLOSED:已销户, FROZEN:冻结)',
    CREATED_BY STRING COMMENT '创建人',
    CREATED_DATE DATE COMMENT '创建日期',
    UPDATED_BY STRING COMMENT '更新人',
    UPDATED_DATE DATE COMMENT '更新日期'
) COMMENT '客户主表' PARTITIONED BY (ETL_DATE STRING) STORED AS ORC LOCATION '/user/hive/warehouse/AML_ODS.db/ODS_AML_CUSTOMER_MASTER' TBLPROPERTIES ("orc.compress" = "SNAPPY");

CREATE EXTERNAL
TABLE IF NOT EXISTS AML_ODS.ODS_AML_MONITORING_RULE (
    RULE_ID STRING COMMENT '规则唯一ID (业务主键)',
    RULE_NAME STRING COMMENT '规则名称',
    RULE_DESC STRING COMMENT '规则描述',
    RULE_TYPE STRING COMMENT '规则类型 (AMOUNT:金额, FREQUENCY:频率, PATTERN:模式, BEHAVIOR:行为)',
    RULE_CATEGORY STRING COMMENT '规则类别 (CASH:现金, TFR:转账, CROSS_BORDER:跨境, GAMBLING:赌博)',
    ACTIVE CHAR(1) COMMENT '是否启用 (Y/N)',
    SEVERITY_LEVEL STRING COMMENT '触发后预警严重等级',
    PARAM_JSON STRING COMMENT '规则参数 (JSON格式存储)',
    SQL_EXPRESSION STRING COMMENT '规则对应的SQL表达式 (可选)',
    LAST_MODIFIED_BY STRING COMMENT '最后修改人',
    LAST_MODIFIED_DATE DATE COMMENT '最后修改日期'
) COMMENT '监控规则表' PARTITIONED BY (ETL_DATE STRING) STORED AS ORC LOCATION '/user/hive/warehouse/AML_ODS.db/ODS_AML_MONITORING_RULE' TBLPROPERTIES ("orc.compress" = "SNAPPY");

CREATE EXTERNAL
TABLE IF NOT EXISTS AML_ODS.ODS_AML_SCREENING_RESULT (
    RESULT_ID BIGINT COMMENT '筛查结果唯一标识ID',
    SCREENING_TYPE STRING COMMENT '筛查类型 (CUSTOMER:客户开户, TRANSACTION:交易, PERIODIC:定期回溯)',
    SCREENING_DATE DATE COMMENT '筛查日期',
    SCREENING_TIME TIMESTAMP COMMENT '筛查时间戳',
    TARGET_TYPE STRING COMMENT '目标类型 (CUSTOMER:客户, ACCT:账户, COUNTERPARTY:交易对手)',
    TARGET_ID BIGINT COMMENT '目标ID (CUSTOMER_ID, ACCOUNT_ID, 或交易对手ID)',
    TARGET_NAME STRING COMMENT '目标名称',
    MATCHED_ENTITY_ID BIGINT COMMENT '匹配的名单条目ID (外键)',
    MATCHED_LIST_ID BIGINT COMMENT '匹配的名单ID (外键)',
    MATCH_SCORE BIGINT COMMENT '匹配度评分 (0-100)',
    MATCH_LEVEL STRING COMMENT '匹配等级 (EXACT:完全匹配, FUZZY_HIGH:模糊高, FUZZY_MED:模糊中, FUZZY_LOW:模糊低)',
    SCREENING_STATUS STRING COMMENT '筛查状态 (PENDING:待审, ALERT:警报, FALSE_POSITIVE:误报, CONFIRMED:确认)',
    REVIEWED_BY STRING COMMENT '审核人',
    REVIEWED_DATE DATE COMMENT '审核日期',
    COMMENTS STRING COMMENT '审核意见',
    CREATED_DATE DATE COMMENT '创建日期'
) COMMENT '筛查结果表' PARTITIONED BY (ETL_DATE STRING) STORED AS ORC LOCATION '/user/hive/warehouse/AML_ODS.db/ODS_AML_SCREENING_RESULT' TBLPROPERTIES ("orc.compress" = "SNAPPY");

CREATE EXTERNAL
TABLE IF NOT EXISTS AML_ODS.ODS_AML_SUSPICIOUS_TXN_REPORT (
    STR_ID BIGINT COMMENT '报告唯一标识ID',
    STR_NO STRING COMMENT '报告编号 (业务主键)',
    CUSTOMER_ID BIGINT COMMENT '涉及客户ID（外键）',
    REPORT_DATE DATE COMMENT '报告生成日期',
    SUBMIT_DATE DATE COMMENT '提交监管机构日期',
    REPORT_STATUS STRING COMMENT '报告状态（DRAFT：草稿， SUBMITTED：已提交， WITHDRAWN：已撤回）',
    REPORT_TYPE STRING COMMENT '报告类型 (INITIAL：初始， AMENDMENT：修正， CLOSURE：结案）',
    CASE_CATEGORY STRING COMMENT '案件类别',
    SUSPICION_BASIS STRING COMMENT '怀疑依据（详细描述）',
    TOTAL_AMOUNT BIGINT COMMENT '涉及总金额',
    CURRENCY STRING COMMENT '涉及币种',
    FIRST_TXN_DATE DATE COMMENT '首笔可疑交易日期',
    LAST_TXN_DATE DATE COMMENT '末笔可疑交易日期',
    RELATED_ALERT_IDS STRING COMMENT '关联的预警ID列表（逗号分隔）',
    FILED_BY STRING COMMENT '填报人',
    FILED_DATE DATE COMMENT '填报日期',
    APPROVED_BY STRING COMMENT '批准人',
    APPROVED_DATE DATE COMMENT '批准日期',
    REGULATOR_REF_NO STRING COMMENT '监管机构接收编号',
    COMMENTS STRING COMMENT '备注'
) COMMENT '可疑交易报告表' PARTITIONED BY (ETL_DATE STRING) STORED AS ORC LOCATION '/user/hive/warehouse/AML_ODS.db/ODS_AML_SUSPICIOUS_TXN_REPORT' TBLPROPERTIES ("orc.compress" = "SNAPPY");

CREATE EXTERNAL
TABLE IF NOT EXISTS AML_ODS.ODS_AML_TRANSACTION_DETAIL (
    TXN_ID BIGINT COMMENT '交易唯一标识ID',
    TXN_SEQ_NO STRING COMMENT '交易流水号',
    ACCOUNT_ID BIGINT COMMENT '账户ID',
    TXN_TYPE STRING COMMENT '交易类型',
    TXN_SUB_TYPE STRING COMMENT '交易子类型',
    TXN_CHANNEL STRING COMMENT '交易渠道',
    TXN_AMOUNT BIGINT COMMENT '交易金额',
    CURRENCY STRING COMMENT '币种',
    TXN_DATE DATE COMMENT '交易日期',
    TXN_TIME TIMESTAMP COMMENT '交易时间',
    TXN_STATUS STRING COMMENT '交易状态',
    CORE_TXN_ID STRING COMMENT '核心交易ID',
    REF_NO STRING COMMENT '参考号',
    REMITTER_NAME STRING COMMENT '汇款人姓名',
    REMITTER_ACCT_NO STRING COMMENT '汇款人账号',
    BENEFICIARY_NAME STRING COMMENT '收款人姓名',
    BENEFICIARY_ACCT_NO STRING COMMENT '收款人账号',
    REMITTER_COUNTRY STRING COMMENT '汇款人国家',
    BENEFICIARY_COUNTRY STRING COMMENT '收款人国家',
    IP_ADDRESS STRING COMMENT 'IP地址',
    DEVICE_ID STRING COMMENT '设备ID',
    GEO_LOCATION STRING COMMENT '地理位置',
    CREATED_DATE DATE COMMENT '创建日期'
) COMMENT '交易明细表' PARTITIONED BY (ETL_DATE STRING) STORED AS ORC LOCATION '/user/hive/warehouse/AML_ODS.db/ODS_AML_TRANSACTION_DETAIL' TBLPROPERTIES ("orc.compress" = "SNAPPY");

CREATE EXTERNAL
TABLE IF NOT EXISTS AML_ODS.ODS_AML_UBO_INFO (
    UBO_ID BIGINT COMMENT 'UBO信息唯一标识ID',
    CUSTOMER_ID BIGINT COMMENT '关联的客户ID',
    UBO_NAME STRING COMMENT '受益所有人姓名',
    UBO_ID_TYPE STRING COMMENT '受益所有人证件类型',
    UBO_ID_NO STRING COMMENT '受益所有人证件号码',
    UBO_SHARE_PERCENT BIGINT COMMENT '持股比例(%)',
    UBO_POSITION STRING COMMENT '职务(如董事,控股股东)',
    UBO_NATIONALITY STRING COMMENT '国籍',
    UBO_RESIDENCE STRING COMMENT '居住地',
    RELATIONSHIP_TYPE STRING COMMENT '关系类型',
    EFFECTIVE_DATE DATE COMMENT '生效日期',
    EXPIRY_DATE DATE COMMENT '失效日期',
    STATUS STRING COMMENT '状态',
    CREATED_DATE DATE COMMENT '创建时间',
    UPDATED_BY STRING COMMENT '更新人',
    UPDATED_DATE DATE COMMENT '更新日期'
) COMMENT '受益所有人信息表' PARTITIONED BY (ETL_DATE STRING) STORED AS ORC LOCATION '/user/hive/warehouse/AML_ODS.db/ODS_AML_UBO_INFO' TBLPROPERTIES ("orc.compress" = "SNAPPY");

CREATE EXTERNAL
TABLE IF NOT EXISTS AML_ODS.ODS_AML_WATCHLIST_DETAIL (
    ENTITY_ID BIGINT COMMENT '名单条目唯一标识ID',
    LIST_ID BIGINT COMMENT '关联名单ID',
    ENTITY_TYPE STRING COMMENT '实体类型(PERSON:个人,ORG:组织)',
    NAME STRING COMMENT '实体名称',
    ALIAS_NAME STRING COMMENT '别名/曾用名',
    ID_TYPE STRING COMMENT '证件类型',
    ID_NO STRING COMMENT '证件号码',
    NATIONALITY STRING COMMENT '国籍',
    BIRTH_DATE DATE COMMENT '出生日期(个人)',
    PLACE_OF_BIRTH STRING COMMENT '出生地(个人)',
    ADDRESS STRING COMMENT '地址',
    LISTED_DATE DATE COMMENT '列入日期',
    DELISTED_DATE DATE COMMENT '移除日期(NULL表示仍在名单)',
    REASON STRING COMMENT '列入原因',
    SANCTION_TYPE STRING COMMENT '制裁类型',
    REFERENCE_INFO STRING COMMENT '参考信息(如决议号)',
    STATUS STRING COMMENT '条目状态',
    CREATED_DATE DATE COMMENT '创建日期',
    UPDATED_DATE DATE COMMENT '更新日期'
) COMMENT '名单明细表' PARTITIONED BY (ETL_DATE STRING) STORED AS ORC LOCATION '/user/hive/warehouse/AML_ODS.db/ODS_AML_WATCHLIST_DETAIL' TBLPROPERTIES ("orc.compress" = "SNAPPY");

CREATE EXTERNAL
TABLE IF NOT EXISTS AML_ODS.ODS_AML_WATCHLIST_MASTER (
    LIST_ID BIGINT COMMENT '名单唯一标识ID',
    LIST_CODE STRING COMMENT '名单代码',
    LIST_NAME STRING COMMENT '名单名称',
    LIST_SOURCE STRING COMMENT '名单来源',
    LIST_TYPE STRING COMMENT '名单类型',
    CURRENCY STRING COMMENT '适用币种 (NULL表示所有币种)',
    COUNTRY STRING COMMENT '适用国家 (NULL表示所有国家)',
    VALID_FROM DATE COMMENT '生效日期',
    VALID_TO DATE COMMENT '失效日期 (NULL表示长期有效)',
    STATUS STRING COMMENT '名单状态',
    DESCRIPTION STRING COMMENT '名单描述',
    UPDATED_DATE DATE COMMENT '最后更新日期'
) COMMENT '名单主表' PARTITIONED BY (ETL_DATE STRING) STORED AS ORC LOCATION '/user/hive/warehouse/AML_ODS.db/ODS_AML_WATCHLIST_MASTER' TBLPROPERTIES ("orc.compress" = "SNAPPY");