CREATE EXTERNAL TABLE IF NOT EXISTS  ODS.ODS_AML_CUSTOMER_MASTER (
CUSTOMER_ID BIGINT COMMENT '客户唯一标识ID (主键)',
CUST_NO STRING COMMENT  '客户编号 (业务主键, 唯一)',
CUST_NAME STRING COMMENT '客户姓名 (个人) / 公司名称 (对公)',
CUST_TYPE STRING COMMENT '客户类型 (IND:个人, CORP:对公)',
ID_TYPE STRING COMMENT '证件类型 (ID_CARD:身份证, PASSPORT:护照, BUS_LIC:营业执照等)',
ID_NO STRING COMMENT '证件号码',
GENDER STRING COMMENT '性别 (仅个人)',
BIRTH_DATE  DATE COMMENT '出生日期 (仅个人)',
NATIONALITY STRING COMMENT '国籍',
RESIDENCE_COUNTRY STRING COMMENT '居住国家',
RESIDENCE_CITY STRING COMMENT '居住城市',
ADDRESS STRING COMMENT '详细地址',
PHONE STRING COMMENT '联系电话',
EMAIL STRING COMMENT '电子邮箱',
OCCUPATION STRING COMMENT' 职业 (仅个人)',
INDUSTRY  STRING COMMENT '所属行业 (仅对公)',
ANNUAL_INCOME  DECIMAL(15,2) COMMENT '年收入 (估算)',
SOURCE_OF_FUNDS  STRING COMMENT '资金来源 (工资、投资、经营等)',
PURPOSE_OF_ACCOUNT  STRING COMMENT '账户用途 (储蓄、投资、贸易等)',
RISK_LEVEL STRING COMMENT '当前风险等级 (LOW, MEDIUM, HIGH, VERY_HIGH)',
RISK_LEVEL_SOURCE STRING COMMENT '风险等级来源 (MANUAL:人工, AUTO:系统自动)',
RISK_ASSESS_DATE DATE COMMENT '最近一次风险评估日期',
OPEN_DATE DATE COMMENT '客户开户日期',
CLOSE_DATE DATE COMMENT '客户销户日期 (NULL表示未销户)',
STATUS STRING COMMENT '客户状态 (ACTIVE:活跃, INACTIVE:休眠, CLOSED:已销户, FROZEN:冻结)',
CREATED_BY STRING COMMENT '创建人',
CREATED_DATE DATE  COMMENT '创建日期',
UPDATED_BY STRING COMMENT'更新人',
UPDATED_DATE DATE  COMMENT '更新日期'
)PARTITIONED BY (ETL_DATE   STRING)
 STORED AS ORC
 LOCATION '/aml/ods/ODS_AML_CUSTOMER_MASTER'
 TBLPROPERTIES ("orc.compress"="SNAPPY") ;


CREATE EXTERNAL TABLE IF NOT EXISTS  ODS.AML_ALERT (
 ALERT_ID            BIGINT COMMENT  '预警唯一标识ID',
 ALERT_NO            STRING COMMENT '预警编号 (业务主键)',
 CUSTOMER_ID         BIGINT COMMENT '关联客户ID (外键)',
 ACCOUNT_ID          BIGINT COMMENT '关联客户ID (外键)',
 RULE_ID             STRING COMMENT '触发规则ID (或模型ID)',
 RULE_NAME           STRING COMMENT '触发规则/模型名称',
 ALERT_TYPE          STRING COMMENT '预警类型 (RULE:规则, MODEL:模型)',
 ALERT_DATE          DATE COMMENT    '预警生成日期',
 ALERT_TIME          TIMESTAMP COMMENT    '预警生成时间戳',
 ALERT_STATUS        STRING COMMENT    '预警状态 (PENDING:待处理, REVIEWING:审核中, DISMISSED:排除, C',
 SEVERITY_LEVEL      STRING COMMENT    '严重等级 (LOW, MEDIUM, HIGH, CRITICAL)',
 SCORE               STRING COMMENT    '模型评分 (若由模型触发)',
 TRIGGER_AMOUNT      STRING COMMENT    '触发交易金额',
 TRIGGER_TXN_COUNT   STRING COMMENT    '触发期间交易笔数',
 DESCRIPTION         STRING COMMENT    '预警描述 (规则/模型触发原因简述)',
 ASSIGNED_TO         STRING COMMENT     '分配给 (分析师)',
 ASSIGNED_DATE       DATE COMMENT     '分配日期',
 REVIEWED_BY         STRING COMMENT     '审核人',
 REVIEWED_DATE       DATE COMMENT     '审核日期',
 COMMENTS            STRING COMMENT     '审核详细意见',
 STR_NO              STRING COMMENT    '关联的可疑交易报告编号 (确认后生成)' ,
 CREATED_DATE        DATE COMMENT    '创建日期' ,
 UPDATED_DATE        DATE COMMENT'更新日期'
)PARTITIONED BY (ETL_DATE   STRING)
    STORED AS ORC
    LOCATION '/aml/ods/ODS_AML_ALERT'
    TBLPROPERTIES ("orc.compress"="SNAPPY") ;

CREATE EXTERNAL TABLE IF NOT EXISTS  ODS.AML_ACCOUNT_MASTER (
  ACCOUNT_ID          STRING COMMENT'账户唯一标识ID',
  ACCT_NO             STRING COMMENT'账户号码(业务主键)',
  CUSTOMER_ID         BIGINT COMMENT'关联账户ID(外键)',
  ACCT_TYPE           STRING COMMENT'账户类型',
  CURRENCY            STRING COMMENT'账户币种',
  OPEN_DATE           DATE COMMENT'账户开户日期',
  CLOSE_DATE          DATE COMMENT'账户销户日期 (NULL表示未销户)',
  STATUS              STRING COMMENT    '账户状态',
  CURRENT_BALANCE     DECIMAL(15,2) COMMENT    '当前余额',
  AVG_DAILY_BALANCE   DECIMAL(15,2) COMMENT '日均余额 (可定期计算)',
  LAST_TXN_DATE       DATE COMMENT  '最后交易日期',
  CHANNEL_OPEN        STRING COMMENT  '开户渠道',
  BRANCH_CODE         STRING COMMENT'开户网点代码',
  BRANCH_NAME         STRING COMMENT'开户网点名称',
  CREATED_BY          STRING COMMENT '创建人',
  CREATED_DATE        DATE COMMENT '创建日期',
  UPDATED_BY          STRING COMMENT  '更新人',
  UPDATED_DATE        DATE  COMMENT'更新日期'
)PARTITIONED BY (ETL_DATE   STRING)
    STORED AS ORC
    LOCATION '/aml/ods/ODS_AML_ACCOUNT_MASTER'
    TBLPROPERTIES ("orc.compress"="SNAPPY") ;